version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    reviewers:
      - willpxrr
    commit_message:
      prefix: "chore"
      include_scope: true
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
    reviewers:
      - willpxrr
    commit_message:
      prefix: "chore"
      include_scope: true
