version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    reviewers:
      - willpxrr
    commit-message:
      prefix: "chore:"
      include: "scope"
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
    reviewers:
      - willpxrr
    commit-message:
      prefix: "chore:"
      include: "scope"
