name: Continuous Integration (Go)

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      isRelease:
        default: false
        type: boolean
        required: true
      goVersion:
        default: '1.17'
        required: false
        type: string
    secrets:
      registryPassword:
        required: true

env:
  GOSUM_PATH: ${{ inputs.path }}/go.sum
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build and Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v1
        with:
          go-version: ${{ inputs.goVersion }}
      - name: Restore Build Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Go Modules
        working-directory: ./${{ inputs.path }}
        run: |
          go mod download
      - name: Ensure Go Modules Consistency
        working-directory: ./${{ inputs.path }}
        run: |
          go mod verify
      - name: Build
        working-directory: ./${{ inputs.path }}/cmd
        run: |
          go build
  artifacts:
    needs:
      - build
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login To The Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.registryPassword }}
      - name: Extract Container Metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ inputs.path }}
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}},enable=${{ inputs.isRelease }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ inputs.isRelease }}
      - name: Build And Push Container
        uses: docker/build-push-action@v2
        with:
          context: ./${{ inputs.path }}
          push: ${{ inputs.isRelease }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
