name: Continuous Integration (React)

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  release:
    types:
      - created

env:
  NODE_VERSION: 17.3
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build and Cache Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Determine Yarn Cache Directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore Build Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-frontend-${{ hashFiles('frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-frontend-
      - name: Build
        working-directory: ./frontend
        run: |
          yarn build
  artifacts:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login To The Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Container Metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-frontend
          flavor: |
            latest=auto
          tags: |
            type=sha,prefix={{branch}}-,enable=${{ !(github.event_name == 'release' && github.event.action == 'created') }}
            type=semver,pattern={{version}},enable=${{ github.event_name == 'release' && github.event.action == 'created' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'release' && github.event.action == 'created' }}
      - name: Build And Push Container
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: ${{ github.event_name == 'release' && github.event.action == 'created' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
